version: "3.9"
   
services:
  web:
    build: .
    restart: always
    volumes:
      - .:/flask
    ports:
      - "8000:5000"
    # image: djangoproject_web:latest
#    container_name: flask_container
    environment:
      FLASK_ENV: development
    links:
      - db

  db:
    image: mysql:5.7.37
    restart: always
    volumes:
#      - ./data/db:/docker-entrypoint-initdb.d/:ro
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=plantdb
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_HOST=localhost
